version: "2"
services:
  namenode:
      image: apache/hadoop:3
      hostname: namenode
      container_name: namenode
      command: ["hdfs", "namenode"]
      ports:
        - 9870:9870
      env_file:
        - ./config
      volumes:
      - ./Hadoop:/data
      environment:
          ENSURE_NAMENODE_DIR: "/tmp/hadoop-root/dfs/name"
      networks:
      - es-net

  datanode1:
      image: apache/hadoop:3
      container_name: datanode1
      command: ["hdfs", "datanode"]
      env_file:
        - ./config
      networks:
      - es-net
      volumes:
      - ./Hadoop:/data

  datanode2:
      image: apache/hadoop:3
      container_name: datanode2
      command: ["hdfs", "datanode"]
      env_file:
        - ./config 
      networks:
      - es-net
      volumes:
      - ./Hadoop:/data

  # datanode3:
  #     image: apache/hadoop:3
  #     container_name: datanode3
  #     command: ["hdfs", "datanode"]
  #     env_file:
  #       - ./config      
  #     networks:
  #     - es-net
  #     volumes:
  #     - ./Hadoop:/data
      
  resourcemanager:
      image: apache/hadoop:3
      hostname: resourcemanager
      command: ["yarn", "resourcemanager"]
      ports:
         - 8088:8088
      env_file:
        - ./config
      # volumes:
      #   - ./test.sh:/opt/test.sh
      networks:
      - es-net
      
  nodemanager:
      image: apache/hadoop:3
      command: ["yarn", "nodemanager"]
      env_file:
        - ./config
      networks:
      - es-net

  spark-master:
    image: bitnami/spark:3.2
    container_name: spark-master
    ports:
      - "8888:8888"
      - "7077:7077"
    volumes:
      - ./Spark:/bitnami
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_WEBUI_PORT=8888
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    networks:
      - es-net

  spark-worker-1:
    image: bitnami/spark:3.2
    container_name: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1024m
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    volumes:
      - ./Spark:/bitnami
    depends_on:
      - spark-master
    networks:
      - es-net

  # spark-worker-2:
  #   image: bitnami/spark:3.2
  #   container_name: spark-worker-2
  #   environment:
  #     - SPARK_MODE=worker
  #     - SPARK_MASTER_URL=spark://spark-master:7077
  #     - SPARK_WORKER_CORES=1
  #     - SPARK_WORKER_MEMORY=1024m
  #     - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
  #   volumes:
  #     - ./Spark:/bitnami
  #   depends_on:
  #     - spark-master
  #   networks:
  #     - es-net


networks:
  es-net:
    driver: bridge